// 定义所有Action的名字
// 用户登录模块
export const LOGIN = 'LOGIN';
export const SET_USER_INFO = 'SET_USET_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const REGISTER = 'REGISTER';
export const GET_SMS_CODE = 'GET_SMS_CODE';
export const VALIDATE_SMS_CODE = 'VALIDATE_SMS_CODE';
export const FORGETPASSWORD = 'FORGETPASSWORD';
export const  RECHANGE= 'RECHANGE';

// 蓝牙通讯模块
export const BLUE_TOOTH_DEVICE = 'BLUE_TOOTH_DEVICE';
export const BLUE_TOOTH_CONNECT_STATE = 'BLUE_TOOTH_CONNECT_STATE';
export const BLUE_TOOTH_ISABLE = 'BLUE_TOOTH_ISABLE';
export const BLUE_TOOTH_READ = 'BLUE_TOOTH_READ';
export const BLUE_TOOTH_SEND = 'BLUE_TOOTH_SEND';
export const SET_BLUE_TOOTH_READ = 'SET_BLUE_TOOTH_READ';
export const USE_BLUE_TOOTH_READ = 'USE_BLUE_TOOTH_READ';
export const GET_BLUE_TOOTH_READ = 'GET_BLUE_TOOTH_READ';

// 参数数据模块
export const SAVE_MEASURE_SERVER = 'SAVE_MEASURE_SERVER';
export const GET_TEMP_MEASURE_SERVER = 'GET_TEMP_MEASURE_SERVER';
export const GET_ECG_MEASURE_SERVER = 'GET_ECG_MEASURE_SERVER';
export const GET_NBP_MEASURE_SERVER = 'GET_NBP_MEASURE_SERVER';
export const GET_SPO2_MEASURE_SERVER = 'GET_SPO2_MEASURE_SERVER';
export const GET_RESP_MEASURE_SERVER = 'GET_RESP_MEASURE_SERVER';

export const SET_TEMP_MEASURE_SERVER = 'SET_TEMP_MEASURE_SERVER';
export const SET_ECG_MEASURE_SERVER = 'SET_ECG_MEASURE_SERVER';
export const SET_NBP_MEASURE_SERVER = 'SET_NBP_MEASURE_SERVER';
export const SET_SPO2_MEASURE_SERVER = 'SET_SPO2_MEASURE_SERVER';
export const SET_RESP_MEASURE_SERVER = 'SET_RESP_MEASURE_SERVER';

export const ABNORMAL_MEASURE = 'ABNORMAL_MEASURE';
export const COUNT_ABNORMAL_TEMP = 'COUNT_ABNORMAL_TEMP';
export const COUNT_ABNORMAL_ECG = 'COUNT_ABNORMAL_ECG';
export const COUNT_ABNORMAL_NBP = 'COUNT_ABNORMAL_NBP';
export const COUNT_ABNORMAL_SPO2 = 'COUNT_ABNORMAL_SPO2';
export const COUNT_ABNORMAL_RESP = 'COUNT_ABNORMAL_RESP';